import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import Header from '@/components/shared/Header';
import './globals.css';

const lato = Lato({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'GPass',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.className} bg-zinc-800`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
